//! Turning the addon's raw positions into a source map v3.
//!
//! The addon hands over BYTE offsets on both sides — it does not know what text
//! will surround the bundle, and converting twice would be twice the chance of
//! getting it wrong. Everything below converts exactly once.
//!
//! **Bytes are not columns.** A source map's line/column are counted in UTF-16
//! code units (what JavaScript calls `.length`), while the offsets coming from
//! Zig are bytes. The bundle header alone (`// Generated by zbundle — ESM…`,
//! `// ── dep.ts ──`) puts an em dash and four box-drawing characters in the
//! way, each three bytes for one code unit — a ten-unit drift before the first
//! statement. Every conversion here therefore decodes the UTF-8 rather than
//! assuming one byte is one column.

/** What the addon returns when `sourcemap` is on. */
export interface RawMap {
  sources: string[];
  sources_content: string[];
  entries: { gen: number; source: number; src: number; name: boolean }[];
}

export interface SourceMapV3 {
  version: 3;
  file?: string;
  sourceRoot?: string;
  sources: string[];
  sourcesContent?: (string | null)[];
  names: string[];
  mappings: string;
}

const B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/**
 * One VLQ base64 field: the value is zig-zagged (sign in bit 0) then emitted in
 * 5-bit groups, low group first, bit 5 saying "another group follows".
 */
export function encodeVlq(value: number): string {
  let v = value < 0 ? (-value << 1) | 1 : value << 1;
  let out = "";
  do {
    let digit = v & 0b11111;
    v >>>= 5;
    if (v > 0) digit |= 0b100000;
    out += B64[digit];
  } while (v > 0);
  return out;
}

/**
 * A byte offset -> (line, column) converter for one text, both counted the way
 * a source map wants them: lines from 0, columns in UTF-16 code units.
 *
 * Built once per file and reused: a bundle asks thousands of times, and the
 * naive "decode from the start every time" is quadratic.
 */
class Positions {
  /** Byte offset of the start of each line. */
  private readonly lineStarts: number[] = [0];
  private readonly bytes: Buffer;

  constructor(text: string) {
    this.bytes = Buffer.from(text, "utf8");
    for (let i = 0; i < this.bytes.length; i++) {
      if (this.bytes[i] === 0x0a) this.lineStarts.push(i + 1);
    }
  }

  at(byteOffset: number): { line: number; column: number } {
    const offset = Math.min(Math.max(byteOffset, 0), this.bytes.length);
    // Binary search: the last line starting at or before the offset.
    let lo = 0;
    let hi = this.lineStarts.length - 1;
    while (lo < hi) {
      const mid = (lo + hi + 1) >> 1;
      if (this.lineStarts[mid]! <= offset) lo = mid;
      else hi = mid - 1;
    }
    const start = this.lineStarts[lo]!;
    // THE conversion: decode the bytes of this line up to the offset, and take
    // the STRING length. That is the column in UTF-16 code units.
    const column = this.bytes.toString("utf8", start, offset).length;
    return { line: lo, column };
  }

  /**
   * The identifier starting at `offset` (a byte offset), or null.
   *
   * Reuses the buffer this object already holds: rebuilding one per lookup
   * turned a linear pass into a quadratic one, and a real bundle asks thousands
   * of times. Only a small window is decoded — no identifier worth naming is
   * longer, and a source is not ASCII, so it must be decoded rather than sliced.
   */
  identifierAt(offset: number): string | null {
    if (offset >= this.bytes.length) return null;
    const window = this.bytes.toString("utf8", offset, Math.min(offset + 64, this.bytes.length));
    const m = /^[\p{ID_Start}$_][\p{ID_Continue}$]*/u.exec(window);
    return m ? m[0] : null;
  }
}

export interface BuildMapOptions {
  /** The bundle's file name, for the `file` field. */
  file?: string;
  /** Paths as they should appear in `sources` (already relative if wanted). */
  sourceNames: string[];
  /** Embed the sources in the map. */
  includeContent: boolean;
  /** Prefixed to every source by the consumer. Omitted entirely when unset. */
  sourceRoot?: string;
}

/**
 * Assembles the v3 map.
 *
 * Segments are sorted by generated position and grouped per generated line;
 * every field but the first of a line is a DELTA against the previous segment,
 * which is what makes a source map compact.
 */
export function buildSourceMap(
  code: string,
  raw: RawMap,
  opts: BuildMapOptions,
): SourceMapV3 {
  const gen = new Positions(code);
  const sources = raw.sources_content.map((c) => new Positions(c));

  // `names` — what makes a debugger show `helper` where the bundle says `a`.
  //
  // Only an IDENTIFIER can have been renamed, and only a renamed one is worth
  // recording: when the emitted text already equals the source text, the
  // debugger reads the source and a name would be dead weight. So a name is
  // added exactly when the two DIFFER.
  const names: string[] = [];
  const nameIndex = new Map<string, number>();
  const intern = (n: string): number => {
    const known = nameIndex.get(n);
    if (known !== undefined) return known;
    nameIndex.set(n, names.length);
    names.push(n);
    return names.length - 1;
  };

  const segments = raw.entries
    .map((e) => {
      const g = gen.at(e.gen);
      const s = sources[e.source]!.at(e.src);
      let name: number | undefined;
      if (e.name) {
        const original = sources[e.source]!.identifierAt(e.src);
        const emitted = gen.identifierAt(e.gen);
        if (original && emitted && original !== emitted) name = intern(original);
      }
      return { genLine: g.line, genCol: g.column, source: e.source, srcLine: s.line, srcCol: s.column, name };
    })
    // A stable order is required by the format, and it also makes the output
    // deterministic — two runs must produce the same bytes.
    .sort((a, b) => a.genLine - b.genLine || a.genCol - b.genCol || a.source - b.source);

  let out = "";
  let lastLine = 0;
  let prevGenCol = 0;
  let prevSource = 0;
  let prevSrcLine = 0;
  let prevSrcCol = 0;
  let prevName = 0;
  let firstInLine = true;

  for (const seg of segments) {
    while (lastLine < seg.genLine) {
      out += ";";
      lastLine++;
      // The generated column restarts at 0 on every line; the other three
      // fields keep running across the whole file.
      prevGenCol = 0;
      firstInLine = true;
    }
    if (!firstInLine) out += ",";
    out += encodeVlq(seg.genCol - prevGenCol);
    out += encodeVlq(seg.source - prevSource);
    out += encodeVlq(seg.srcLine - prevSrcLine);
    out += encodeVlq(seg.srcCol - prevSrcCol);
    prevGenCol = seg.genCol;
    prevSource = seg.source;
    prevSrcLine = seg.srcLine;
    prevSrcCol = seg.srcCol;
    // The fifth field, present only on the segments that carry a name. A
    // four-field and a five-field segment may sit side by side; the `names`
    // index is relative like the others, and only advances when one is written.
    if (seg.name !== undefined) {
      out += encodeVlq(seg.name - prevName);
      prevName = seg.name;
    }
    firstInLine = false;
  }

  const map: SourceMapV3 = {
    version: 3,
    sources: opts.sourceNames,
    names,
    mappings: out,
  };
  if (opts.file) map.file = opts.file;
  // Set only when asked: `sourceRoot: ""` is a value, and "no sourceRoot" is a
  // different statement that some consumers treat differently.
  if (opts.sourceRoot !== undefined) map.sourceRoot = opts.sourceRoot;
  if (opts.includeContent) map.sourcesContent = raw.sources_content;
  return map;
}

/**
 * How one source path is written into `sources`.
 *
 * **Relative to the MAP, never to the cwd.** That is where a debugger resolves
 * them from, and it is what makes a map survive being moved with its bundle.
 *
 * **Always POSIX separators.** `sources` entries are URL-ish; a Windows `\`
 * would be read as an escape, not a directory. A bundle built on Windows and
 * opened on Linux has to work.
 *
 * **`file://` when no relative path exists.** On Windows a source on another
 * drive cannot be reached relatively at all — `path.relative` returns an
 * absolute path — and an absolute Windows path is not a valid `sources` entry.
 * An absolute URL is the honest answer there.
 */
export function sourceEntry(mapDir: string, sourcePath: string, rel: (from: string, to: string) => string, isAbs: (p: string) => boolean, sep: string, toUrl: (p: string) => string): string {
  const r = rel(mapDir, sourcePath);
  if (r === "" || isAbs(r) || /^[A-Za-z]:/.test(r)) return toUrl(sourcePath);
  return r.split(sep).join("/");
}

/** The trailing comment that points a debugger at the map. */
export function sourceMappingURLComment(url: string): string {
  return `\n//# sourceMappingURL=${url}\n`;
}

/** The map as a data URL, for the `inline` mode. */
export function inlineDataUrl(map: SourceMapV3): string {
  const json = JSON.stringify(map);
  return `data:application/json;charset=utf-8;base64,${Buffer.from(json, "utf8").toString("base64")}`;
}
